---
- name: What is my computer information
  hosts: all
  gather_facts: no
  
  tasks:
  
  - name: Issue the powershell command to get the current computer info
    register: powershellresult
    ansible.builtin.win_shell: Get-ComputerInfo
    
    
  - name: Printing powershellresult out
    ansible.builtin.debug:
      var: powershellresult