---
- name: Test cmd from win_command module
  hosts: all
  gather_facts: False

  tasks:

    - name: Run netstat and return Ethernet stats to variable.
      register: netstat_output
      ansible.builtin.win_command: netstat -e
    
    - name: Printing netstat_output
      ansible.builtin.debug:
        var: netstat_output