---
  - name: Control AWS instances
    hosts: localhost
    connection: local
    gather_facts: no
    vars:
       region: ''
       servername: ''
       vault_password: '/var/lib/awx/.ssh/vault_password'

    tasks:

    - name: Get instances id with tag {{ servername }} in {{ region }}
      register: instance_info
      amazon.aws.ec2_instance_info:
       region: "{{ region }}"
       filters:
         "tag:Name": "{{ servername }}"
         instance-state-name: [ "running"]
         "tag:Contact": "{{ my_email_address }}"
      
    - name: Printing out instance_info.instances[0].instance_id
      when: instance_info.instances[0].instance_id is defined
      ansible.builtin.debug:
         msg: "{{ instance_info.instances[0].instance_id }}"

    - name: get the Administrator password
      register: admin_passwd
      no_log: true
      ignore_errors: true
      community.aws.ec2_win_password:
        instance_id: "{{ instance_info.instances[0].instance_id }}"
        region: "{{ region }}"
        key_data: "{{ zigfreed_private_key }}"
        wait: true
        wait_timeout: 45

    # Make the admin password available to other playbooks
    - name: Capture the admin password
      no_log: true
      ignore_errors: true
      ansible.builtin.set_stats:
        data:
          my_secret: "{{ admin_passwd.win_password }}"

    - name: Capture public dns name
      register: my_server
      ansible.builtin.set_stats:
        data:
          my_server: "{{ instance_info.instances[0].public_dns_name }}"

    #- name: Write the Administrator password to the vault
    #  ansible.builtin.shell:
    #    cmd: ansible-vault encrypt_string --vault-password-file "{{ vault_password }}" "{{ admin_passwd.win_password }}" --name 'my_vaulted_secret'
    #    chdir: /var/tmp

    #- name: Read the contents of the vault
    #  ansible.builtin.debug: var="/var/tmp/my_vaulted_secret" --vault-password-file "{{ vault_password }}"

    - name: WTF
      delegate_to: 127.0.0.1
      ansible.builtin.shell:
        cmd: whoami; pwd; uname -n