---
  - name: Control AWS instances
    hosts: localhost
    connection: local
    gather_facts: no
    vars:
       region: ''
       servername: ''

    tasks:

    - name: Get instances id with tag {{ servername }} in {{ region }}
      register: instance_info
      amazon.aws.ec2_instance_info:
       region: "{{ region }}"
       filters:
         "tag:Name": "{{ servername }}"
         instance-state-name: [ "running"]
         "tag:Contact": "{{ my_email_address }}"
      
    - name: Printing out instance_info.instances[0].instance_id
      when: instance_info.instances[0].instance_id is defined
      ansible.builtin.debug:
         msg: "{{ instance_info.instances[0].instance_id }}"

    - name: get the Administrator password
      register: admin_passwd
      community.aws.ec2_win_password:
        instance_id: "{{ instance_info.instances[0].instance_id }}"
        region: "{{ region }}"
        key_data: "{{ zigfreed_private_key }}"
        wait: true
        wait_timeout: 45

    - name: "Printing the admin password: {{ admin_passwd.win_password }}"
      ansible.builtin.debug:
        msg: "{{ admin_passwd.win_password }}"

    # Make the admin password available to other playbooks
    - name: Capture the admin password
      no_log: true
      ansible.builtin.set_stats:
        data:
          my_secret: "{{ admin_passwd.win_password }}"

    - name: Printing the public dns name
      ansible.builtin.debug:
        msg:  "{{ instance_info.instances[0].public_dns_name }}"