---
  - name: Control AWS instances
    hosts: localhost
    connection: local
    gather_facts: no
    vars:
       region: ''
       servername: ''

    tasks:

    - name: Get instances id with tag {{ servername }} in {{ region }}
      register: instance_info
      amazon.aws.ec2_instance_info:
       region: "{{ region }}"
       filters:
         "tag:Name": "{{ servername }}"
         instance-state-name: [ "running"]
         "tag:Contact": "{{ my_email_address }}"
      
    - name: Printing out instance_info.instances[0].instance_id
      when: instance_info.instances[0].instance_id is defined
      ansible.builtin.debug:
         msg: "{{ instance_info.instances[0].instance_id }}"

    - name: get the Administrator password
      register: admin_passwd
      no_log: true
      ignore_errors: true
      community.aws.ec2_win_password:
        instance_id: "{{ instance_info.instances[0].instance_id }}"
        region: "{{ region }}"
        key_data: "{{ zigfreed_private_key }}"
        wait: true
        wait_timeout: 45

    # Make the admin password available to other playbooks
    - name: Capture the admin password
      no_log: true
      ignore_errors: true
      ansible.builtin.set_stats:
        data:
          my_secret: "{{ admin_passwd.win_password }}"

    - name: Capture public dns name
      ansible.builtin.set_stats:
        data:
          my_server: "{{ instance_info.instances[0].public_dns_name }}"

    - name: Make the my_server variable active in this playbook
      ansible.builtin.set_fact:
        my_server: "{{ instance_info.instances[0].public_dns_name }}"

    - name: Create the host_vars for this servername
      ansible.builtin.file:
        path: "{{ playbook_dir }}/host_vars/{{ my_server }}"
        state: directory

    - name: Write password to the vault
      no_log: true
      ignore_errors: true
      ansible.builtin.copy:
        content: "{{ admin_passwd.win_password }}"
        dest: "{{ playbook_dir }}/host_vars/{{ my_server }}/vault"

    - name: display multiple file contents
      with_file:
        - "{{ playbook_dir }}/host_vars/{{ my_server }}/vault"
      ansible.builtin.debug: var=item