---
- name: Build our custom website
  hosts: "{{ my_server }}"
  gather_facts: no
  vars:
    iis_sites:
      - name: 'Ansible'
        port: '80'
        path: 'C:\sites\dailydemo'
    iis_test_message: "Hello World!  My test IIS Server"
    ansible_user: Administrator
    ansible_password: "{{ my_secret }}"
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5986

  tasks:

    - name: Install IIS Webserver
      ansible.builtin.win_feature:
        name: Web-Server
        state: present

    - name: Create site directory structure
      ansible.builtin.win_file:
        path: 'C:\sites\dailydemo'
        state: directory

    - name: Create IIS site
      notify: restart iis service
      ansible.builtin.win_iis_website:
        name: 'AnsibleDemo'
        state: started
        port: 80
        physical_path: 'C:\sites\dailydemo'
      
    - name: Open port for site on the firewall
      with_items: "{{ iis_sites }}"
      ansible.builtin.win_firewall_rule:
        name: "iisport{{ item.port }}"
        enable: yes
        state: present
        localport: "{{ item.port }}"
        action: Allow
        direction: In
        protocol: Tcp
      
    - name: Template simple web site to iis_site_path as index.html
      with_items: "{{ iis_sites }}"
      ansible.builtin.win_template:
        src: 'index.html.j2'
        dest: '{{ item.path }}\index.html'
      
    - name: Show website addresses
      loop:
        - http://{{ ansible_host }}
      ansible.builtin.debug:
        msg: "{{ item }}"
      
  handlers:

    - name: restart iis service
      ansible.builtin.win_service:
        name: W3Svc
        state: restarted
        start_mode: auto