---
- name: Chocolatey Facts and Configuration
  hosts: all
  gather_facts: false
  
  tasks:

  - name: Gather facts from Chocolatey
    chocolatey.chocolatey.win_chocolatey_facts:

  - name: Displays the gathered facts
    ansible.builtin.debug:
      var: ansible_chocolatey