---
- name: Creating an Incident Ticket because something went wrong
  hosts: localhost
  gather_facts: yes
  
  tasks:

    - name: Create the incident ticket
      register: record
      servicenow.itsm.incident:
        instance:
          host: "https://{{ servicenow_url }}"
          username: "{{ username }}"
          password: "{{ password }}"
        state: new
        caller: "{{ caller_name }}"
        short_description: Ansible Automation Platform playbook has errored out
        description: "foobar"
        impact: low
        urgency: low
        other:
          assignment_group: "Ansible West Tigers"

    - name: Capture the Incident Ticket number 
      ansible.builtin.set_stats:
        data:
          incident_ticket: "{{ record.number }}"