---
- name: Creating an Incident Ticket because something went wrong
  hosts: localhost
  gather_facts: no
  
  tasks:

    - name: Create the incident ticket
      register: incident_info
      servicenow.itsm.incident:
        instance:
          host: "https://{{ servicenow_url }}"
          username: "{{ username }}"
          password: "{{ password }}"
        state: new
        caller: "{{ caller_name }}"
        short_description: "Ansible Automation Platform - Job ID: {{ my_job_id }} - Template named: {{ my_job_template_name }} - failure see description."
        description: "Job ID: {{ my_job_id }} \n Template named: {{ my_job_template_name }} \n Message: {{ my_error }}"
        impact: low
        urgency: low
        other:
          assignment_group: "Ansible West Tigers"

    - name: Print out the Incident info
      ansible.builtin.debug:
        var: incident_info.record.number

    - name: Capture the Incident Ticket number 
      ansible.builtin.set_stats:
        data:
          incident_ticket: "{{ incident_info.record.number }}"